theme: jekyll-theme-minimal
title: Luming Liang
email: llmpass@gmail.com
description: 
Senior Researcher at Microsoft Applied Sciences Group
Education
Ph.D Colorado School of Mines Computer Science (Minor geophysics)
